sudo: false
language: cpp

#branches:
#  only:
#    - master

git:
  submodules:
    true

os: 
  - linux

addons:
  apt:
    update: true
    #sources:
      #- ubuntu-toolchain-r-test
    packages:
      # Docs
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      # Build
      #- gcc-6
      #- g++-6
      # Code Coverage
      - lcov

before_install:
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      CMAKE_INSTALLER=install-cmake.sh && \
        curl -sSL https://github.com/Kitware/CMake/releases/download/v3.14.1/cmake-3.14.1-Linux-x86_64.sh -o ${CMAKE_INSTALLER} && \
        chmod +x ${CMAKE_INSTALLER} && \
        sudo ./${CMAKE_INSTALLER} --prefix=/usr/local --skip-license
    fi
  - alias cmake=/usr/local/bin/cmake
  - export PATH=/usr/local/bin/cmake/bin:/usr/local/bin:${PATH}
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      echo "need cmake 3.12" && \
        brew update && \
        brew install ccache && \
        brew upgrade cmake && \
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
    fi
  # Install Eigen
  - wget http://bitbucket.org/eigen/eigen/get/3.3.5.zip -O eigen.zip
  - unzip eigen.zip -d dependencies
  - mv dependencies/eig* dependencies/eigen
  # Build
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  # Docs
  - cd docs
  - doxygen Doxyfile
  - cd ..
  # Building
  - $CXX --version
  - cmake --version
  - mkdir -p build && cd build
  - cmake ..
  - cmake --build .
  # Code Coverage
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'eigen/*' 'googletest/*' '/usr/include/*' '/usr/lib/*' 'src/3rd-party/*' '/usr/include/*' '/usr/lib/*' -o coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  # Tests
  # Valgrind

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    
notifications:
  email: false

