sudo: false
language: cpp

#branches:
#  only:
#    - master

git:
  submodules:
    true

os: 
  - linux
dist: xenial

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # Docs
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      # Build
      - cmake
      - gcc-6
      - g++-6
      # Code Coverage
      - lcov


script:
  # Docs
  - cd docs
  - doxygen Doxyfile
  - cd ..
  # Building
  - $CXX --version
  - cmake --version
  - mkdir -p build && cd build
  - cmake -DCODE_COVERAGE=ON ..
  - cmake --build . 
  # Tests
  #- ctest # useless to run two times this tests 
  - ./Riemann-Geometrie --gtest_output="xml:../docs/GoogleTestReport.xml"
  # Code Coverage
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'eigen/*' 'googletest/*' '/usr/include/*' '/usr/lib/*' 'src/3rd-party/*' '/usr/include/*' '/usr/lib/*' -o coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  # Valgrind

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    
notifications:
  email: false

