version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
install:
- ps: git submodule --quiet update --init --recursive
build:
  project: Riemann-Geometrie.sln
  parallel: true
  verbosity: quiet
after_test:
- ps: C:\projects\riemann-geometrie\build\Release-x64\GoogleTest.exe --gtest_output="xml:..\..\doc\GoogleTestReport.xml"
deploy: off